artifacts_root: artifacts/

source_url: https://drive.google.com/uc?id=1B1JfG5bGH0vGlijL2n90DAeCoCLdD67o
local_data_file: artifacts/data/data.zip
data_path: artifacts/data/

pre_process_file: artifacts/data/twitter.csv
post_process_files: ["train.csv", "valid.csv", "test.csv"]

col_names: ["target", "ids", "date", "flag", "user", "text"]
text_col: "text"
target_col: "target"

fasttext_embedding: artifacts/Fasttext/embeddings/embeddings.npz
fasttext_embed_matrix: artifacts/Test/embeddings.npy
fasttext_model: artifacts/Test/fasttext_combine.model
fasttext_tokenizer: artifacts/Test/keras_combine_tokenizer.json
embedding_paths: ["artifacts/Fasttext/embeddings/", "artifacts/BERT/embeddings/", "artifacts/labels/"]

bert_embedding: artifacts/BERT/embeddings/embeddings.npz
bert_tokenizer: artifacts/BERT/tokenizer
bert_model: artifacts/BERT/model

labels: artifacts/labels/labels.npz
models_path: artifacts/Models/
