bert_argument:
  model_name: bert-base-multilingual-cased
  max_seq_length: 32

fasttext_argument:
  vector_size: 300
  max_seq_length: 32
  epochs: 100
  word_count: 10000

epochs: 10

ntscraper:
  log_level: 1
  skip_instance_check: False
  